apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: 4.11.1
    helm:
      values: |
        agent:
          enabled: false
        collector:
          image:
            registry: 10.20.20.201:5000
            repository: jaegertracing/jaeger
            tag: 2.19.0
          replicaCount: 1
          service:
            type: ClusterIP
        esIndexCleaner:
          enabled: false
        esRollover:
          enabled: false
        global:
          imageRegistry: 10.20.20.201:5000
        image:
          pullPolicy: IfNotPresent
          registry: 10.20.20.201:5000
          repository: jaegertracing/jaeger
          tag: 2.19.0
        query:
          image:
            registry: 10.20.20.201:5000
            repository: jaegertracing/jaeger
            tag: 2.19.0
          replicaCount: 1
          service:
            type: ClusterIP
        spark:
          enabled: false
        sparkDependencies:
          enabled: false
        storage:
          type: memory
        userconfig:
          exporters:
            jaeger_storage_exporter:
              trace_storage: primary_store
          extensions:
            healthcheckv2:
              http:
                endpoint: 0.0.0.0:13133
              use_v2: true
            jaeger_query:
              base_path: /jaeger
              storage:
                traces: primary_store
            jaeger_storage:
              backends:
                primary_store:
                  badger:
                    directories:
                      keys: /badger/keys
                      values: /badger/values
                    ephemeral: false
                    ttl:
                      spans: 720h
                    metrics_update_interval: 10s
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
          service:
            extensions:
            - jaeger_storage
            - jaeger_query
            - healthcheckv2
            pipelines:
              traces:
                exporters:
                - jaeger_storage_exporter
                receivers:
                - otlp
        jaeger:
          extraVolumes:
            - name: badger-data
              persistentVolumeClaim:
                claimName: jaeger-badger-data
          extraVolumeMounts:
            - name: badger-data
              mountPath: /badger
          podSecurityContext:
            fsGroup: 10001
            runAsGroup: 10001
            runAsUser: 0
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
