apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: qti-api-gateway
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Merpatidove/QTI-MAGANG.git
    targetRevision: main
    path: api-gateway/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: qti
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
